In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [4]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [5]:
print(f'X.shape[1]= {X.shape[1]}')
print(f'wh = \n {wh}\n')
print(f'bh = \n {bh}\n')
print(f'wout = \n {wout}\n')
print(f'bout = \n {bout}\n')

X.shape[1]= 4
wh = 
 [[0.47546471 0.73993944 0.18013886]
 [0.31287196 0.26961258 0.32856566]
 [0.48472493 0.97650586 0.20616255]
 [0.90364807 0.89844097 0.89388715]]

bh = 
 [[0.36371443 0.58292481 0.09438722]]

wout = 
 [[0.81814447]
 [0.40162515]
 [0.22377611]]

bout = 
 [[0.04451827]]



# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [6]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
   

In [7]:
print(f'hidden_layer_input = \n {hidden_layer_input}\n')
print(f'hiddenlayer_activations = \n {hiddenlayer_activations}\n')


hidden_layer_input = 
 [[1.32390407 2.29937011 0.48068863]
 [2.22755213 3.19781109 1.37457578]
 [1.58023446 1.75097836 1.31684003]]

hiddenlayer_activations = 
 [[0.78983051 0.90882486 0.61791047]
 [0.90269656 0.96075182 0.79811843]
 [0.82923772 0.85207616 0.78865549]]



In [8]:
for i in  range ( epoch ) :
    #Forward Propogation
    output_layer_input1 = np.dot( hiddenlayer_activations, wout) 
    output_layer_input = output_layer_input1 + bout
    output =  derivatives_sigmoid(output_layer_input) 
   

In [10]:
print(f'output_layer_input = \n {output_layer_input}\n')
print(f'output = \n {output}\n')


output_layer_input = 
 [[1.19399426]
 [1.3475164 ]
 [1.241652  ]]

output = 
 [[-0.23162803]
 [-0.46828405]
 [-0.30004769]]



In [12]:
print ( f"output of Forward Propogation:\n{output} \n") 
print ( f"wout of Backpropagation:\n{wout}\n")
print ( f"bout of Backpropagation:\n{bout}\n")

output of Forward Propogation:
[[-0.23162803]
 [-0.46828405]
 [-0.30004769]] 

wout of Backpropagation:
[[0.81814447]
 [0.40162515]
 [0.22377611]]

bout of Backpropagation:
[[0.04451827]]

