In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [4]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [6]:
print(f'X.shape[1]= {X.shape[1]}')
print(f'wh = \n {wh}\n')
print(f'bh = \n {bh}\n')
print(f'wout = \n {wout}\n')
print(f'bout = \n {bout}\n')

X.shape[1]= 4
wh = 
 [[0.87631888 0.28713645 0.3067132 ]
 [0.17607711 0.70084905 0.78030301]
 [0.18238334 0.48764805 0.44490742]
 [0.02640247 0.06893001 0.56110297]]

bh = 
 [[0.63475579 0.86519446 0.59169102]]

wout = 
 [[0.70048181]
 [0.67183918]
 [0.20066888]]

bout = 
 [[0.26041398]]



# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [7]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
   

In [8]:
print(f'hidden_layer_input = \n {hidden_layer_input}\n')
print(f'hiddenlayer_activations = \n {hiddenlayer_activations}\n')


hidden_layer_input = 
 [[1.69345801 1.63997896 1.34331164]
 [1.71986048 1.70890898 1.90441461]
 [0.83723537 1.63497353 1.93309699]]

hiddenlayer_activations = 
 [[0.84467838 0.83753207 0.79303401]
 [0.84811086 0.84669472 0.87039036]
 [0.69788263 0.83684982 0.87359181]]



In [9]:
for i in  range ( epoch ) :
    #Forward Propogation
    output_layer_input1 = np.dot( hidden_layer_input, wout) 
    output_layer_input = output_layer_input1 + bout
    output =  derivatives_sigmoid(output_layer_input) 
   

In [10]:
print(f'output_layer_input = \n {hidden_layer_input}\n')
print(f'output = \n {hiddenlayer_activations}\n')


output_layer_input = 
 [[1.69345801 1.63997896 1.34331164]
 [1.71986048 1.70890898 1.90441461]
 [0.83723537 1.63497353 1.93309699]]

output = 
 [[0.84467838 0.83753207 0.79303401]
 [0.84811086 0.84669472 0.87039036]
 [0.69788263 0.83684982 0.87359181]]



In [7]:
print ( f"output of Forward Propogation:\n{output} \n") 
print ( f"wout of Backpropagation:\n{wout}\n")
print ( f"bout of Backpropagation:\n{bout}\n")

output of Forward Propogation:
[[-10.68002739]
 [-21.22951088]
 [ -4.85374782]] 

wout of Backpropagation:
[[0.58796202]
 [0.70861283]
 [0.92437601]]

bout of Backpropagation:
[[0.59171531]]

