In [1]:
import numpy as np

#Input array
X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [2]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [3]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [4]:
#weight and bias initialization
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [5]:
print(f'X.shape[1]= {X.shape[1]}')
print(f'wh = \n {wh}\n')
print(f'bh = \n {bh}\n')
print(f'wout = \n {wout}\n')
print(f'bout = \n {bout}\n')

X.shape[1]= 4
wh = 
 [[0.36124571 0.0516458  0.44022221]
 [0.58769202 0.61012895 0.25665259]
 [0.03824144 0.81089666 0.68448556]
 [0.95961504 0.78364576 0.25771059]]

bh = 
 [[0.74423777 0.29661454 0.58586049]]

wout = 
 [[0.44232493]
 [0.26564681]
 [0.99560216]]

bout = 
 [[0.14755941]]



# 作業 
* 請參閱範例中的 hidden Layer 寫法, 完成 output Layer 的程式

In [33]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
    
    output_layer_input1 = np.dot( hiddenlayer_activations, wout) 
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input) 

In [38]:
print(f'hiddenlayer_activations = \n {hiddenlayer_activations}\n')
print (f"output of Forward Propogation:\n{output} \n") 

hiddenlayer_activations = 
 [[0.75836288 0.7611795  0.84690997]
 [0.89122738 0.87465973 0.87742612]
 [0.90817436 0.84427534 0.75030201]]

output of Forward Propogation:
[[0.6142119 ]
 [0.62717047]
 [0.62663167]] 



In [36]:
B_wout = derivatives_sigmoid(wout)
B_bout = derivatives_sigmoid(bout)

In [37]:
print ( f"wout of Backpropagation:\n{B_wout}\n")
print ( f"bout of Backpropagation:\n{B_bout}\n")

wout of Backpropagation:
[[0.18582573]
 [0.15702293]
 [0.00435933]]

bout of Backpropagation:
[[0.10996361]]

